############################
## CHANGE THESE
############################

baseURL: 'https://admatthews.co.uk/'
title: 'Adam Matthews'

############################
## MODULES
############################

module:
  imports:
    - path: github.com/chrede88/L1nkr


############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-gb'


