############################
## Author
############################

author:
  name: "Adam Matthews"
  image: headshot-sq.png
  greeting: "Greetings, Welcome, Bonjour! :evergreen_tree:"
  icon: ":wave:"

############################
## Links
############################

links:
  - github: https://github.com/adamsthws
#  - link: https://github.com/Chrede88/L1nkr#readme
  - website: https://wonkatron.com
  # - x-twitter: 
  - mastodon: https://mastodon.social/@wonkatron
  - linkedin: https://www.linkedin.com/in/adamatthews/
  - instagram: https://www.instagram.com/adamsthws
  # - reddit: 
  - telegram: https://t.me/wonkatron
  - whatsapp: https://wa.me/+447966614062
  - signal: https://signal.me/#eu/ETvmROZeHolwP-YJNMLANlSbOsANdtm5jAIA6yQCLmmEOjVr4cNBopgmsFuFImX5
  # - codepen: 
  # - dev: 
  - email: adam@admatthews.com
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  - paypal: https://paypal.me/adamsthws
  # - windows:

############################
## Colunms of Links
############################

# between 2 & 6 columns are supported (both incl)
columns: 3

###########################
## Icon text
###########################

# add the icon name to each icon
icontext: true

############################
## Tooltips
############################

# add tooltips on all icons
tooltip: true

###############################
## OpenGraph & Twitter Cards
###############################

title: "Adam Matthews"
description: "Built with L1nkr & Hugo"
images:
  - thumbnail.png
