# Cloudflare Pages configuration.
# See https://developers.cloudflare.com/pages/functions/wrangler-configuration/

# Disable Cloudflare metrics collection
send_metrics=false

# Default worker name (used if no --env is passed)
name = "admatthews-co-uk"

# Directory where the built site output is located
pages_build_output_dir = "public"

# Build environment variables
[vars]
# renovate: datasource=github-tags depName=golang/go
GO_VERSION = "1.23.2"
# renovate: datasource=github-releases depName=gohugoio/hugo
HUGO_VERSION = "0.136.5"
